/* Generated By:JJTree: Do not edit this line. ANDCondition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ANDCondition extends SimpleNode {
  public ANDCondition(int id) {
    super(id);
  }

  public ANDCondition(CCALParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4bd8e69b6ccc59d3403b72abe7a7274e (do not edit this line) */
