/* Generated By:JJTree: Do not edit this line. AssignStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class AssignStatement extends SimpleNode {
  public AssignStatement(int id) {
    super(id);
  }

  public AssignStatement(CCALParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5abbfbb1edbc37b8410167ceaf1e6dc7 (do not edit this line) */
