/* Generated By:JavaCC: Do not edit this line. CCALParserVisitor.java Version 5.0 */
public interface CCALParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(Prog node, Object data);
  public Object visit(VarDec node, Object data);
  public Object visit(Id node, Object data);
  public Object visit(ConstDec node, Object data);
  public Object visit(Function node, Object data);
  public Object visit(Return node, Object data);
  public Object visit(Type node, Object data);
  public Object visit(ParameterList node, Object data);
  public Object visit(Main node, Object data);
  public Object visit(Statement node, Object data);
  public Object visit(Assign node, Object data);
  public Object visit(FuncAssign node, Object data);
  public Object visit(PlusOp node, Object data);
  public Object visit(MinusOp node, Object data);
  public Object visit(Num node, Object data);
  public Object visit(BoolOp node, Object data);
  public Object visit(FuncReturn node, Object data);
  public Object visit(Comparison node, Object data);
  public Object visit(EQComp node, Object data);
  public Object visit(NEComp node, Object data);
  public Object visit(LTComp node, Object data);
  public Object visit(LEComp node, Object data);
  public Object visit(GTComp node, Object data);
  public Object visit(GEComp node, Object data);
  public Object visit(ORCondition node, Object data);
  public Object visit(ANDCondition node, Object data);
  public Object visit(ArgList node, Object data);
}
/* JavaCC - OriginalChecksum=6adcd924c86d47facd18602ad4dcd164 (do not edit this line) */
