/* Generated By:JavaCC: Do not edit this line. CCALParserTreeConstants.java Version 5.0 */
public interface CCALParserTreeConstants
{
  public int JJTPROG = 0;
  public int JJTVOID = 1;
  public int JJTVARDEC = 2;
  public int JJTID = 3;
  public int JJTCONSTDEC = 4;
  public int JJTFUNCTION = 5;
  public int JJTRETURN = 6;
  public int JJTTYPE = 7;
  public int JJTPARAMETERLIST = 8;
  public int JJTMAIN = 9;
  public int JJTSTATEMENT = 10;
  public int JJTASSIGN = 11;
  public int JJTFUNCASSIGN = 12;
  public int JJTPLUSOP = 13;
  public int JJTMINUSOP = 14;
  public int JJTNUM = 15;
  public int JJTBOOLOP = 16;
  public int JJTFUNCRETURN = 17;
  public int JJTCOMPARISON = 18;
  public int JJTEQCOMP = 19;
  public int JJTNECOMP = 20;
  public int JJTLTCOMP = 21;
  public int JJTLECOMP = 22;
  public int JJTGTCOMP = 23;
  public int JJTGECOMP = 24;
  public int JJTORCONDITION = 25;
  public int JJTANDCONDITION = 26;
  public int JJTARGLIST = 27;


  public String[] jjtNodeName = {
    "Prog",
    "void",
    "VarDec",
    "Id",
    "ConstDec",
    "Function",
    "Return",
    "Type",
    "ParameterList",
    "Main",
    "Statement",
    "Assign",
    "FuncAssign",
    "PlusOp",
    "MinusOp",
    "Num",
    "BoolOp",
    "FuncReturn",
    "Comparison",
    "EQComp",
    "NEComp",
    "LTComp",
    "LEComp",
    "GTComp",
    "GEComp",
    "ORCondition",
    "ANDCondition",
    "ArgList",
  };
}
/* JavaCC - OriginalChecksum=a05d097e6aed11e639f1db0ea9487d50 (do not edit this line) */
