/* Generated By:JJTree: Do not edit this line. FuncAssignm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class FuncAssignm extends SimpleNode {
  public FuncAssignm(int id) {
    super(id);
  }

  public FuncAssignm(CCALParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ec45f7108b6c1c7fcdc394f30ce18396 (do not edit this line) */
